import type { DirectoryInfo } from "./types";

/**
 * Curated list of free web directories that accept site submissions.
 * Each entry has been verified as live. Only free submission tiers included.
 * Last verified: March 2026
 */
const directories: DirectoryInfo[] = [
  // ====================================================================
  //  GENERAL WEB DIRECTORIES — direct submit.php / form pages
  // ====================================================================
  {
    id: "somuch",
    name: "SoMuch.com",
    url: "https://www.somuch.com",
    submitUrl: "https://www.somuch.com/submit-links/",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    active: true,
  },
  {
    id: "jayde",
    name: "Jayde",
    url: "https://www.jayde.com",
    submitUrl: "https://www.jayde.com/submit.html",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "abc-directory",
    name: "ABC Directory",
    url: "https://www.abc-directory.com",
    submitUrl: "https://www.abc-directory.com/submiturl",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "viesearch",
    name: "VieSearch",
    url: "https://viesearch.com",
    submitUrl: "https://viesearch.com/submit",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    active: true,
  },
  {
    id: "cipinet",
    name: "Cipinet",
    url: "https://www.cipinet.com",
    submitUrl: "https://www.cipinet.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "ontoplist",
    name: "OnTopList",
    url: "https://www.ontoplist.com",
    submitUrl: "https://www.ontoplist.com/add-your-business-listing/",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    active: true,
  },
  {
    id: "exactseek",
    name: "ExactSeek",
    url: "https://www.exactseek.com",
    submitUrl: "https://www.exactseek.com/add.html",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "sitepromotiondirectory",
    name: "Site Promotion Directory",
    url: "https://www.sitepromotiondirectory.com",
    submitUrl: "https://www.sitepromotiondirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "marketinginternetdirectory",
    name: "Marketing Internet Directory",
    url: "https://www.marketinginternetdirectory.com",
    submitUrl: "https://www.marketinginternetdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "ukinternetdirectory",
    name: "UK Internet Directory",
    url: "https://www.ukinternetdirectory.net",
    submitUrl: "https://www.ukinternetdirectory.net/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "britainbusinessdirectory",
    name: "Britain Business Directory",
    url: "https://www.britainbusinessdirectory.com",
    submitUrl: "https://www.britainbusinessdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "freewebsubmission",
    name: "Free Web Submission",
    url: "https://www.freewebsubmission.com",
    submitUrl: "https://www.freewebsubmission.com/submit-a-search-engine.html",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: false,
    notes: "Submits to multiple search engines at once",
    active: true,
  },
  {
    id: "prolinkdirectory",
    name: "Pro Link Directory",
    url: "https://www.prolinkdirectory.com",
    submitUrl: "https://www.prolinkdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "alive2directory",
    name: "Alive2 Directory",
    url: "https://www.alive2directory.com",
    submitUrl: "https://www.alive2directory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "ecobluedirectory",
    name: "EcoBlue Directory",
    url: "https://www.ecobluedirectory.com",
    submitUrl: "https://www.ecobluedirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "interesting-dir",
    name: "Interesting Directory",
    url: "https://www.interesting-dir.com",
    submitUrl: "https://www.interesting-dir.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "afunnydir",
    name: "AFunny Directory",
    url: "https://www.afunnydir.com",
    submitUrl: "https://www.afunnydir.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "arcticdirectory",
    name: "Arctic Directory",
    url: "https://www.arcticdirectory.com",
    submitUrl: "https://www.arcticdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "pegasus-dir",
    name: "Pegasus Directory",
    url: "https://www.pegasusdirectory.com",
    submitUrl: "https://www.pegasusdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 21,
    doFollow: false,
    active: true,
  },
  {
    id: "worldweb-directory",
    name: "WorldWeb Directory",
    url: "https://www.worldweb-directory.com",
    submitUrl: "https://www.worldweb-directory.com/add.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "webguiding",
    name: "WebGuiding",
    url: "https://www.webguiding.net",
    submitUrl: "https://www.webguiding.net/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "propellerdir",
    name: "Propeller Directory",
    url: "https://www.propellerdir.com",
    submitUrl: "https://www.propellerdir.com/submit",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "directory-free",
    name: "Directory Free",
    url: "https://www.directory-free.com",
    submitUrl: "https://www.directory-free.com/submit/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "sites-plus",
    name: "Sites Plus",
    url: "https://www.sites-plus.com",
    submitUrl: "https://www.sites-plus.com/submit",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "1websdirectory",
    name: "1Webs Directory",
    url: "https://www.1websdirectory.com",
    submitUrl: "https://www.1websdirectory.com/submit-site/",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "alabamaindex",
    name: "Alabama Index",
    url: "https://www.alabamaindex.com",
    submitUrl: "https://www.alabamaindex.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "directorystaff",
    name: "Directory Staff",
    url: "https://www.directorystaff.com",
    submitUrl: "https://www.directorystaff.com/submit",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "tsection",
    name: "TSection",
    url: "https://www.tsection.com",
    submitUrl: "https://www.tsection.com/submit",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "businessseek",
    name: "BusinessSeek",
    url: "https://www.businessseek.biz",
    submitUrl: "https://www.businessseek.biz/page.php?page=link-submit-options",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "expansiondirectory",
    name: "Expansion Directory",
    url: "https://expansiondirectory.com",
    submitUrl: "https://expansiondirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "directory3",
    name: "Directory3",
    url: "https://directory3.org",
    submitUrl: "https://directory3.org/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "sublimelink",
    name: "Sublime Link",
    url: "https://sublimelink.org",
    submitUrl: "https://sublimelink.org/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "spillbean",
    name: "SpillBean",
    url: "https://www.spillbean.com",
    submitUrl: "https://www.spillbean.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "informationcrawler",
    name: "Information Crawler",
    url: "https://www.informationcrawler.com",
    submitUrl: "https://www.informationcrawler.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "postfreedirectory",
    name: "Post Free Directory",
    url: "https://www.postfreedirectory.com",
    submitUrl: "https://www.postfreedirectory.com/submit",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "excitedirectory",
    name: "Excite Directory",
    url: "https://www.excitedirectory.com",
    submitUrl: "https://www.excitedirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "besttopdir",
    name: "Best Top Directory",
    url: "https://besttopdir.info",
    submitUrl: "https://besttopdir.info/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "seorange",
    name: "SEO Range",
    url: "https://www.seorange.com",
    submitUrl: "https://www.seorange.com/submit",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    active: true,
  },
  {
    id: "seodeeplinks",
    name: "SEO Deep Links",
    url: "https://www.seodeeplinks.net",
    submitUrl: "https://www.seodeeplinks.net/submit",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    active: true,
  },
  {
    id: "directory-wgshost",
    name: "WGS Directory",
    url: "https://directory.wgshost.com",
    submitUrl: "https://directory.wgshost.com/submit",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "seo-wgsmedia",
    name: "WGS Media SEO",
    url: "https://seo.wgsmedia.net",
    submitUrl: "https://seo.wgsmedia.net/submit",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "hitwebdirectory",
    name: "Hit Web Directory",
    url: "https://hitwebdirectory.com",
    submitUrl: "https://hitwebdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "digabusiness",
    name: "DigaBusiness",
    url: "https://digabusiness.com",
    submitUrl: "https://digabusiness.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "9sites",
    name: "9sites.net",
    url: "https://9sites.net",
    submitUrl: "https://9sites.net/addurl.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    active: true,
  },
  {
    id: "freeprwebdirectory",
    name: "Free PR Web Directory",
    url: "https://freeprwebdirectory.com",
    submitUrl: "https://freeprwebdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "4ni",
    name: "4NI",
    url: "https://4ni.co.uk",
    submitUrl: "https://4ni.co.uk/submitsite.aspx",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    notes: "Northern Ireland directory",
    active: true,
  },
  {
    id: "directory4",
    name: "Directory4",
    url: "https://directory4.org",
    submitUrl: "https://directory4.org/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  // ====================================================================
  //  BLOG DIRECTORIES
  // ====================================================================
  {
    id: "bloggingfusion",
    name: "Blogging Fusion",
    url: "https://www.bloggingfusion.com",
    submitUrl: "https://www.bloggingfusion.com/submit/",
    type: "blog",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    notes: "Major blog directory",
    active: true,
  },
  // ====================================================================
  //  LOCAL / BUSINESS DIRECTORIES
  // ====================================================================
  {
    id: "hotfrog",
    name: "Hotfrog",
    url: "https://www.hotfrog.com",
    submitUrl: "https://www.hotfrog.com/add-your-business",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    active: true,
  },
  {
    id: "brownbook",
    name: "Brownbook",
    url: "https://www.brownbook.net",
    submitUrl: "https://www.brownbook.net/add-listing/",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    active: true,
  },
  {
    id: "cylex",
    name: "Cylex",
    url: "https://www.cylex.com",
    submitUrl: "https://www.cylex.com/add-company.html",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: false,
    active: true,
  },
  {
    id: "lawyer-directory",
    name: "Lawyer Directory",
    url: "https://lawyer-directory.net",
    submitUrl: "https://lawyer-directory.net/add-listing.php",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    notes: "Niche legal directory",
    active: true,
  },
  {
    id: "poweredindia",
    name: "Powered India",
    url: "https://www.poweredindia.com",
    submitUrl: "https://www.poweredindia.com/register/index.php",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: false,
    notes: "India business directory",
    active: true,
  },
  {
    id: "vandanayellowpages",
    name: "Vandana Yellow Pages",
    url: "https://www.vandanayellowpages.com",
    submitUrl: "https://www.vandanayellowpages.com/register/",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: false,
    notes: "India yellow pages",
    active: true,
  },
  {
    id: "australiawebdirectory",
    name: "Australia Web Directory",
    url: "https://australiawebdirectory.net",
    submitUrl: "https://australiawebdirectory.net/submit.php",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    notes: "Australia-specific directory",
    active: true,
  },
  {
    id: "directory-com-au",
    name: "Directory.com.au",
    url: "https://directory.com.au",
    submitUrl: "https://directory.com.au/add-listing/",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    notes: "Australia business directory",
    active: true,
  },
  // ====================================================================
  //  NICHE / TECH / STARTUP DIRECTORIES
  // ====================================================================
  {
    id: "launchingnext",
    name: "Launching Next",
    url: "https://www.launchingnext.com",
    submitUrl: "https://www.launchingnext.com/submit/",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    active: true,
  },
  {
    id: "toolspedia",
    name: "Toolspedia",
    url: "https://www.toolspedia.io",
    submitUrl: "https://www.toolspedia.io/submit-tool",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    active: true,
  },
  {
    id: "betalist",
    name: "BetaList",
    url: "https://betalist.com",
    submitUrl: "https://betalist.com/submit",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    notes: "For startups in beta",
    active: true,
  },
  {
    id: "startupstash",
    name: "Startup Stash",
    url: "https://startupstash.com",
    submitUrl: "https://startupstash.com/submit/",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: true,
    active: true,
  },
  {
    id: "alternativeto",
    name: "AlternativeTo",
    url: "https://alternativeto.net",
    submitUrl: "https://alternativeto.net/add-app/",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    notes: "For software/apps/tools",
    active: true,
  },
  {
    id: "producthunt",
    name: "Product Hunt",
    url: "https://www.producthunt.com",
    submitUrl: "https://www.producthunt.com/posts/new",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    notes: "Very high authority",
    active: true,
  },
  {
    id: "saasworthy",
    name: "SaaSworthy",
    url: "https://www.saasworthy.com",
    submitUrl: "https://www.saasworthy.com/list-product",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    active: true,
  },
  {
    id: "capterra",
    name: "Capterra",
    url: "https://www.capterra.com",
    submitUrl: "https://www.capterra.com/vendors/sign-up",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: true,
    notes: "High DA — for software",
    active: true,
  },
  {
    id: "g2",
    name: "G2",
    url: "https://www.g2.com",
    submitUrl: "https://www.g2.com/products/new",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: true,
    notes: "Very high DA — for software",
    active: true,
  },
  {
    id: "crunchbase",
    name: "Crunchbase",
    url: "https://www.crunchbase.com",
    submitUrl: "https://www.crunchbase.com/add-new",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    notes: "Very high DA — businesses/startups",
    active: true,
  },
  {
    id: "f6s",
    name: "F6S",
    url: "https://www.f6s.com",
    submitUrl: "https://www.f6s.com/create/startup",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    notes: "For startups",
    active: true,
  },
  {
    id: "saashub",
    name: "SaaSHub",
    url: "https://www.saashub.com",
    submitUrl: "https://www.saashub.com/submit",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    notes: "Software directory with alternatives",
    active: true,
  },
  {
    id: "designdirectory",
    name: "Design Directory",
    url: "https://designdirectory.com",
    submitUrl: "https://designdirectory.com/submit",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    notes: "Design-focused directory",
    active: true,
  },
  // ====================================================================
  //  SOCIAL BOOKMARK / WEB 2.0
  // ====================================================================
  {
    id: "folkd",
    name: "Folkd",
    url: "https://www.folkd.com",
    submitUrl: "https://www.folkd.com/submit/",
    type: "social-bookmark",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    active: true,
  },
  {
    id: "slashdot",
    name: "Slashdot",
    url: "https://slashdot.org",
    submitUrl: "https://slashdot.org/submission",
    type: "social-bookmark",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    active: true,
  },
  // ====================================================================
  //  MORE VERIFIED GENERAL DIRECTORIES (from user's extended list)
  // ====================================================================
  {
    id: "a1webdirectory",
    name: "A1 Web Directory",
    url: "https://www.a1webdirectory.org",
    submitUrl: "https://www.a1webdirectory.org/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 30,
    doFollow: false,
    active: true,
  },
  {
    id: "siteswebdirectory",
    name: "Sites Web Directory",
    url: "https://www.siteswebdirectory.com",
    submitUrl: "https://www.siteswebdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "submissionwebdirectory",
    name: "Submission Web Directory",
    url: "https://www.submissionwebdirectory.com",
    submitUrl: "https://www.submissionwebdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "highrankdirectory",
    name: "High Rank Directory",
    url: "https://www.highrankdirectory.com",
    submitUrl: "https://www.highrankdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "target-directory",
    name: "Target Directory",
    url: "https://www.target-directory.com",
    submitUrl: "https://www.target-directory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "anoox",
    name: "Anoox",
    url: "https://www.anoox.com",
    submitUrl: "https://www.anoox.com/add-your-site.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: true,
    notes: "Social search engine",
    active: true,
  },
  {
    id: "activesearchresults",
    name: "Active Search Results",
    url: "https://www.activesearchresults.com",
    submitUrl: "https://www.activesearchresults.com/addurl.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: true,
    active: true,
  },
  {
    id: "directoryfire",
    name: "Directory Fire",
    url: "https://www.directoryfire.com",
    submitUrl: "https://www.directoryfire.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "gainweb",
    name: "GainWeb",
    url: "https://gainweb.org",
    submitUrl: "https://gainweb.org/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "webglance",
    name: "WebGlance",
    url: "https://webglance.com",
    submitUrl: "https://webglance.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "promotebusinessdirectory",
    name: "Promote Business Directory",
    url: "https://www.promotebusinessdirectory.com",
    submitUrl: "https://www.promotebusinessdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "usawebsitesdirectory",
    name: "USA Websites Directory",
    url: "https://www.usawebsitesdirectory.com",
    submitUrl: "https://www.usawebsitesdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "qualityinternetdirectory",
    name: "Quality Internet Directory",
    url: "https://qualityinternetdirectory.com",
    submitUrl: "https://qualityinternetdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "canadiandirectory",
    name: "Canadian Directory",
    url: "https://canadiandirectory.org",
    submitUrl: "https://canadiandirectory.org/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    notes: "Canada-focused directory",
    active: true,
  },
  {
    id: "weboworld",
    name: "WeboWorld",
    url: "https://www.weboworld.com",
    submitUrl: "https://www.weboworld.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "linkspurt",
    name: "LinkSpurt",
    url: "https://linkspurt.com",
    submitUrl: "https://linkspurt.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "weblink-directory",
    name: "WebLink Directory",
    url: "https://weblink.directory",
    submitUrl: "https://weblink.directory/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "dmozing",
    name: "Dmozing",
    url: "https://www.dmozing.com",
    submitUrl: "https://www.dmozing.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "daduru",
    name: "Daduru",
    url: "https://www.daduru.com",
    submitUrl: "https://www.daduru.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "seekdragon",
    name: "SeekDragon",
    url: "https://www.seekdragon.com",
    submitUrl: "https://www.seekdragon.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "herbusinesslistings",
    name: "Her Business Listings",
    url: "https://herbusinesslistings.com",
    submitUrl: "https://herbusinesslistings.com/submit.php",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    notes: "Women-owned business directory",
    active: true,
  },
  {
    id: "blpdirectory",
    name: "BLP Directory",
    url: "https://blpdirectory.info",
    submitUrl: "https://blpdirectory.info/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "moonsunfavor",
    name: "MoonSunFavor",
    url: "https://moonsunfavor.com",
    submitUrl: "https://moonsunfavor.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "linkforfree",
    name: "Link For Free",
    url: "https://linkforfree.com.ar",
    submitUrl: "https://linkforfree.com.ar/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "hostingtres",
    name: "HostingTres",
    url: "https://hostingtres.com",
    submitUrl: "https://hostingtres.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "hostingtres-ar",
    name: "HostingTres AR",
    url: "https://hostingtres.com.ar",
    submitUrl: "https://hostingtres.com.ar/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "goaflam",
    name: "Goaflam",
    url: "https://goaflam.net",
    submitUrl: "https://goaflam.net/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "infoxia",
    name: "Infoxia",
    url: "https://infoxia.com",
    submitUrl: "https://infoxia.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "dir-submitter",
    name: "Dir Submitter",
    url: "https://dir-submitter.info",
    submitUrl: "https://dir-submitter.info/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "morefunz",
    name: "MoreFunz",
    url: "https://morefunz.com",
    submitUrl: "https://morefunz.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "uksmall-business",
    name: "UK Small Business",
    url: "https://uksmall.business",
    submitUrl: "https://uksmall.business/submit/",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    notes: "UK small business directory",
    active: true,
  },
  {
    id: "akama",
    name: "Akama",
    url: "https://akama.com",
    submitUrl: "https://akama.com/submit",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "hub-biz",
    name: "Hub.biz",
    url: "https://hub.biz",
    submitUrl: "https://hub.biz/submit",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "merchantcircle",
    name: "MerchantCircle",
    url: "https://www.merchantcircle.com",
    submitUrl: "https://www.merchantcircle.com/signup",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    notes: "US local business directory — high DA",
    active: true,
  },
  {
    id: "allpages",
    name: "AllPages",
    url: "https://www.allpages.com",
    submitUrl: "https://www.allpages.com/add-listing/",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: false,
    active: true,
  },
];

export default directories;
