import type { DirectoryInfo } from "./types";

/**
 * Curated list of free web directories that accept site submissions.
 * Each entry includes the submission URL, type, and expected behavior.
 * Only directories with free submission tiers are included.
 */
const directories: DirectoryInfo[] = [
  // ============ General Web Directories ============
  {
    id: "jasmine-dir",
    name: "Jasmine Directory",
    url: "https://www.jasminedirectory.com",
    submitUrl: "https://www.jasminedirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 30,
    doFollow: false,
    notes: "Well-maintained human-reviewed directory",
    active: true,
  },
  {
    id: "alive-dir",
    name: "Alive Directory",
    url: "https://www.alivedirectory.com",
    submitUrl: "https://www.alivedirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "somuch",
    name: "SoMuch.com",
    url: "https://www.somuch.com",
    submitUrl: "https://www.somuch.com/submit-links/",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    active: true,
  },
  {
    id: "abilogic",
    name: "Abilogic",
    url: "https://www.abilogic.com",
    submitUrl: "https://www.abilogic.com/addurl.html",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "pegasus-dir",
    name: "Pegasus Directory",
    url: "https://www.pegasusdirectory.com",
    submitUrl: "https://www.pegasusdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 21,
    doFollow: false,
    active: true,
  },
  {
    id: "one-mission",
    name: "One Mission",
    url: "https://www.onemission.com",
    submitUrl: "https://www.onemission.com/submit/",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "9sites",
    name: "9sites.net",
    url: "https://www.9sites.net",
    submitUrl: "https://www.9sites.net/addurl.html",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    active: true,
  },
  {
    id: "dir-org",
    name: "Directory.org",
    url: "https://www.directory.org",
    submitUrl: "https://www.directory.org/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 30,
    doFollow: false,
    active: true,
  },
  {
    id: "mastermoz",
    name: "MasterMoz",
    url: "https://www.mastermoz.com",
    submitUrl: "https://www.mastermoz.com/add_url.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "el-dir",
    name: "eLib Directory",
    url: "https://www.elib.org",
    submitUrl: "https://www.elib.org/add.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "fired-dir",
    name: "Fired Directory",
    url: "https://www.fireddirectory.com",
    submitUrl: "https://www.fireddirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "prolinkdirectory",
    name: "Pro Link Directory",
    url: "https://www.prolinkdirectory.com",
    submitUrl: "https://www.prolinkdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "info-listing",
    name: "Info Listing",
    url: "https://www.info-listing.com",
    submitUrl: "https://www.info-listing.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "webwiki",
    name: "WebWiki",
    url: "https://www.webwiki.com",
    submitUrl: "https://www.webwiki.com/submit",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: true,
    active: true,
  },
  {
    id: "yellowbot",
    name: "YellowBot",
    url: "https://www.yellowbot.com",
    submitUrl: "https://www.yellowbot.com/addlisting",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: false,
    active: true,
  },
  {
    id: "hotfrog",
    name: "Hotfrog",
    url: "https://www.hotfrog.com",
    submitUrl: "https://www.hotfrog.com/add-your-business",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    active: true,
  },
  {
    id: "spoke",
    name: "Spoke.com",
    url: "https://www.spoke.com",
    submitUrl: "https://www.spoke.com/create/company",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: false,
    active: true,
  },
  {
    id: "brownbook",
    name: "Brownbook",
    url: "https://www.brownbook.net",
    submitUrl: "https://www.brownbook.net/add-listing/",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    active: true,
  },
  {
    id: "cylex",
    name: "Cylex",
    url: "https://www.cylex.com",
    submitUrl: "https://www.cylex.com/add-company.html",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: false,
    active: true,
  },
  {
    id: "tupalo",
    name: "Tupalo",
    url: "https://www.tupalo.co",
    submitUrl: "https://www.tupalo.co/register",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    active: true,
  },
  // ============ Blog / Article Directories ============
  {
    id: "blogarama",
    name: "Blogarama",
    url: "https://www.blogarama.com",
    submitUrl: "https://www.blogarama.com/submit-blog",
    type: "blog",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: true,
    active: true,
  },
  {
    id: "globeofblogs",
    name: "Globe of Blogs",
    url: "https://www.globeofblogs.com",
    submitUrl: "https://www.globeofblogs.com/submit_blog.php",
    type: "blog",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "blogtopsites",
    name: "Blog TopSites",
    url: "https://www.blogtopsites.com",
    submitUrl: "https://www.blogtopsites.com/signup/",
    type: "blog",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    active: true,
  },
  {
    id: "blogflux",
    name: "BlogFlux",
    url: "https://www.blogflux.com",
    submitUrl: "https://www.blogflux.com/suggest.php",
    type: "blog",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "bloglisting",
    name: "Blog Listing",
    url: "https://www.bloglisting.net",
    submitUrl: "https://www.bloglisting.net/submit.php",
    type: "blog",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: false,
    active: true,
  },
  // ============ RSS Directories ============
  {
    id: "feedburner-alt",
    name: "RSS Micro",
    url: "https://www.rssmicro.com",
    submitUrl: "https://www.rssmicro.com/submitrss.aspx",
    type: "rss",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: false,
    active: true,
  },
  {
    id: "feedage",
    name: "Feedage",
    url: "https://www.feedage.com",
    submitUrl: "https://www.feedage.com/submit/",
    type: "rss",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: false,
    active: true,
  },
  // ============ Social Bookmark / Web2.0 ============
  {
    id: "folkd",
    name: "Folkd",
    url: "https://www.folkd.com",
    submitUrl: "https://www.folkd.com/submit/",
    type: "social-bookmark",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    active: true,
  },
  {
    id: "slashdot",
    name: "Slashdot",
    url: "https://slashdot.org",
    submitUrl: "https://slashdot.org/submission",
    type: "social-bookmark",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    active: true,
  },
  {
    id: "diigo",
    name: "Diigo",
    url: "https://www.diigo.com",
    submitUrl: "https://www.diigo.com/post",
    type: "social-bookmark",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: false,
    active: true,
  },
  // ============ Niche / Tech ============
  {
    id: "alternativeto",
    name: "AlternativeTo",
    url: "https://alternativeto.net",
    submitUrl: "https://alternativeto.net/add-app/",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    notes: "For software/apps/tools only",
    active: true,
  },
  {
    id: "producthunt",
    name: "Product Hunt",
    url: "https://www.producthunt.com",
    submitUrl: "https://www.producthunt.com/posts/new",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    notes: "For products/tools — very high authority",
    active: true,
  },
  {
    id: "saasworthy",
    name: "SaaSworthy",
    url: "https://www.saasworthy.com",
    submitUrl: "https://www.saasworthy.com/list-product",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    notes: "For SaaS products",
    active: true,
  },
  {
    id: "capterra",
    name: "Capterra",
    url: "https://www.capterra.com",
    submitUrl: "https://www.capterra.com/vendors/sign-up",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: true,
    notes: "For software products — high DA",
    active: true,
  },
  {
    id: "g2",
    name: "G2",
    url: "https://www.g2.com",
    submitUrl: "https://www.g2.com/products/new",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: true,
    notes: "For software products — very high DA",
    active: true,
  },
  {
    id: "getapp",
    name: "GetApp",
    url: "https://www.getapp.com",
    submitUrl: "https://www.getapp.com/submit",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: true,
    active: true,
  },
  {
    id: "crunchbase",
    name: "Crunchbase",
    url: "https://www.crunchbase.com",
    submitUrl: "https://www.crunchbase.com/add-new",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    notes: "For businesses/startups — very high DA",
    active: true,
  },
  {
    id: "f6s",
    name: "F6S",
    url: "https://www.f6s.com",
    submitUrl: "https://www.f6s.com/create/startup",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    notes: "For startups",
    active: true,
  },
  {
    id: "startupranking",
    name: "Startup Ranking",
    url: "https://www.startupranking.com",
    submitUrl: "https://www.startupranking.com/startup/create",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: false,
    active: true,
  },
  {
    id: "betalist",
    name: "BetaList",
    url: "https://betalist.com",
    submitUrl: "https://betalist.com/submit",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    notes: "For startups in beta",
    active: true,
  },
  {
    id: "launchingnext",
    name: "Launching Next",
    url: "https://www.launchingnext.com",
    submitUrl: "https://www.launchingnext.com/submit/",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    active: true,
  },
  {
    id: "startupstash",
    name: "Startup Stash",
    url: "https://startupstash.com",
    submitUrl: "https://startupstash.com/submit/",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: true,
    active: true,
  },
  {
    id: "toolspedia",
    name: "Toolspedia",
    url: "https://www.toolspedia.io",
    submitUrl: "https://www.toolspedia.io/submit-tool",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    active: true,
  },
  // ============ More General Directories ============
  {
    id: "entireweb",
    name: "EntireWeb",
    url: "https://www.entireweb.com",
    submitUrl: "https://www.entireweb.com/submit/",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: false,
    active: true,
  },
  {
    id: "linkcentre",
    name: "Link Centre",
    url: "https://www.linkcentre.com",
    submitUrl: "https://www.linkcentre.com/addurl/",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "a1webdirectory",
    name: "A1 Web Directory",
    url: "https://www.a1webdirectory.org",
    submitUrl: "https://www.a1webdirectory.org/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 30,
    doFollow: false,
    active: true,
  },
  {
    id: "sitepromotiondirectory",
    name: "Site Promotion Directory",
    url: "https://www.sitepromotiondirectory.com",
    submitUrl: "https://www.sitepromotiondirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "freedirectorysubmit",
    name: "Free Directory Submit",
    url: "https://www.freedirectorysubmit.com",
    submitUrl: "https://www.freedirectorysubmit.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: false,
    active: true,
  },
  {
    id: "addgoodsites",
    name: "Add Good Sites",
    url: "https://www.addgoodsites.com",
    submitUrl: "https://www.addgoodsites.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "marketinginternetdirectory",
    name: "Marketing Internet Directory",
    url: "https://www.marketinginternetdirectory.com",
    submitUrl: "https://www.marketinginternetdirectory.com/submit.php",
    type: "general",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: false,
    active: true,
  },
  {
    id: "thetoolbus",
    name: "The Tool Bus",
    url: "https://www.thetoolbus.ai",
    submitUrl: "https://www.thetoolbus.ai/submit",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    notes: "AI tools directory",
    active: true,
  },
  {
    id: "futurepedia",
    name: "Futurepedia",
    url: "https://www.futurepedia.io",
    submitUrl: "https://www.futurepedia.io/submit-tool",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    notes: "AI tools directory",
    active: true,
  },
  {
    id: "thereisanaiforthat",
    name: "There Is An AI For That",
    url: "https://theresanaiforthat.com",
    submitUrl: "https://theresanaiforthat.com/submit/",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    notes: "AI tools directory — very high traffic",
    active: true,
  },
  {
    id: "toolify",
    name: "Toolify.ai",
    url: "https://www.toolify.ai",
    submitUrl: "https://www.toolify.ai/submit",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: true,
    notes: "AI tools directory",
    active: true,
  },
  // ============ More Local / Business ============
  {
    id: "elocal",
    name: "eLocal",
    url: "https://www.elocal.com",
    submitUrl: "https://www.elocal.com/add-listing",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: false,
    active: true,
  },
  {
    id: "manta",
    name: "Manta",
    url: "https://www.manta.com",
    submitUrl: "https://www.manta.com/claim",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: true,
    notes: "US business directory — high DA",
    active: true,
  },
  {
    id: "dandb",
    name: "Dun & Bradstreet",
    url: "https://www.dnb.com",
    submitUrl: "https://www.dnb.com/duns-number.html",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: true,
    notes: "Business directory — very high DA",
    active: true,
  },
  {
    id: "chamberofcommerce",
    name: "Chamber of Commerce",
    url: "https://www.chamberofcommerce.com",
    submitUrl: "https://www.chamberofcommerce.com/add-business",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    active: true,
  },
  {
    id: "fyple",
    name: "Fyple",
    url: "https://www.fyple.com",
    submitUrl: "https://www.fyple.com/add-company/",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: false,
    active: true,
  },
  {
    id: "showmelocal",
    name: "ShowMeLocal",
    url: "https://www.showmelocal.com",
    submitUrl: "https://www.showmelocal.com/register.aspx",
    type: "local",
    method: "form-post",
    free: true,
    approxApprovalDays: 3,
    doFollow: false,
    active: true,
  },
  {
    id: "nexustechlist",
    name: "Nexus TechList",
    url: "https://www.nexustechlist.com",
    submitUrl: "https://www.nexustechlist.com/submit",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    notes: "Tech tools directory",
    active: true,
  },
  {
    id: "sideprojects",
    name: "SideProjectors",
    url: "https://www.sideprojectors.com",
    submitUrl: "https://www.sideprojectors.com/project/new",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 1,
    doFollow: true,
    notes: "For side projects and small tools",
    active: true,
  },
  {
    id: "saashub",
    name: "SaaSHub",
    url: "https://www.saashub.com",
    submitUrl: "https://www.saashub.com/submit",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 7,
    doFollow: true,
    notes: "Software directory with alternatives",
    active: true,
  },
  {
    id: "webdesigndir",
    name: "Best Web Design Agencies",
    url: "https://www.bestwebdesignagencies.com",
    submitUrl: "https://www.bestwebdesignagencies.com/add-agency",
    type: "niche",
    method: "form-post",
    free: true,
    approxApprovalDays: 14,
    doFollow: true,
    notes: "For web design / digital agencies",
    active: true,
  },
];

export default directories;
