import type { BookmarkPlatform } from "./types";

/**
 * Database of social bookmarking platforms.
 * Curated list of active, free platforms for SEO backlink building.
 * Sorted by DA (domain authority) descending.
 */
const platforms: BookmarkPlatform[] = [
  // ========== High DA (80+) ==========
  {
    id: "reddit",
    name: "Reddit",
    url: "https://www.reddit.com",
    submitUrl: "https://www.reddit.com/submit",
    type: "social",
    da: 96,
    doFollow: false,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Submit to relevant subreddits. Nofollow but high traffic.",
    active: true,
  },
  {
    id: "medium",
    name: "Medium",
    url: "https://medium.com",
    submitUrl: "https://medium.com/new-story",
    type: "content",
    da: 95,
    doFollow: false,
    free: true,
    requiresAccount: true,
    method: "manual",
    notes: "Write articles with links back to your content.",
    active: true,
  },
  {
    id: "pinterest",
    name: "Pinterest",
    url: "https://www.pinterest.com",
    submitUrl: "https://www.pinterest.com/pin-creation-tool/",
    type: "social",
    da: 94,
    doFollow: false,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Pin your content with keyword-rich descriptions.",
    active: true,
  },
  {
    id: "tumblr",
    name: "Tumblr",
    url: "https://www.tumblr.com",
    submitUrl: "https://www.tumblr.com/new/link",
    type: "social",
    da: 93,
    doFollow: false,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Share links as link posts on your Tumblr blog.",
    active: true,
  },
  {
    id: "flickr",
    name: "Flickr",
    url: "https://www.flickr.com",
    submitUrl: "https://www.flickr.com/groups",
    type: "social",
    da: 92,
    doFollow: false,
    free: true,
    requiresAccount: true,
    method: "manual",
    notes: "Share images with links in descriptions.",
    active: true,
  },
  {
    id: "digg",
    name: "Digg",
    url: "https://digg.com",
    submitUrl: "https://digg.com/submit",
    type: "social",
    da: 92,
    doFollow: true,
    free: true,
    requiresAccount: false,
    method: "form-post",
    notes: "Dofollow links. Submit news and articles.",
    active: true,
  },
  {
    id: "scoopit",
    name: "Scoop.it",
    url: "https://www.scoop.it",
    submitUrl: "https://www.scoop.it/new",
    type: "bookmarking",
    da: 92,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. Curate content on topic pages.",
    active: true,
  },
  {
    id: "slashdot",
    name: "Slashdot",
    url: "https://slashdot.org",
    submitUrl: "https://slashdot.org/submission",
    type: "community",
    da: 91,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. Tech/science content submission.",
    active: true,
  },
  {
    id: "flipboard",
    name: "Flipboard",
    url: "https://flipboard.com",
    submitUrl: "https://flipboard.com/",
    type: "social",
    da: 91,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "manual",
    notes: "Dofollow. Flip articles to your magazines.",
    active: true,
  },
  {
    id: "diigo",
    name: "Diigo",
    url: "https://www.diigo.com",
    submitUrl: "https://www.diigo.com/post",
    type: "bookmarking",
    da: 90,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. Save and tag bookmarks publicly.",
    active: true,
  },
  {
    id: "metafilter",
    name: "MetaFilter",
    url: "https://www.metafilter.com",
    submitUrl: "https://www.metafilter.com/contribute/post_good.mefi",
    type: "community",
    da: 87,
    doFollow: true,
    free: false,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. $5 signup. High quality community.",
    active: false,
  },
  {
    id: "mix",
    name: "Mix (StumbleUpon)",
    url: "https://mix.com",
    submitUrl: "https://mix.com/add",
    type: "bookmarking",
    da: 86,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. Successor to StumbleUpon.",
    active: true,
  },
  {
    id: "pearltrees",
    name: "Pearltrees",
    url: "https://www.pearltrees.com",
    submitUrl: "https://www.pearltrees.com/",
    type: "bookmarking",
    da: 85,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. Visual bookmarking and organization.",
    active: true,
  },
  {
    id: "pocket",
    name: "Pocket",
    url: "https://getpocket.com",
    submitUrl: "https://getpocket.com/save",
    type: "bookmarking",
    da: 82,
    doFollow: false,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Mozilla-owned. Save articles for later.",
    active: true,
  },
  {
    id: "minds",
    name: "Minds",
    url: "https://www.minds.com",
    submitUrl: "https://www.minds.com/newsfeed/subscriptions",
    type: "social",
    da: 82,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. Open-source social network.",
    active: true,
  },
  {
    id: "plurk",
    name: "Plurk",
    url: "https://www.plurk.com",
    submitUrl: "https://www.plurk.com/",
    type: "social",
    da: 80,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. Timeline-based social network.",
    active: true,
  },

  // ========== Mid DA (60-79) ==========
  {
    id: "folkd",
    name: "Folkd",
    url: "https://www.folkd.com",
    submitUrl: "https://www.folkd.com/submit/",
    type: "bookmarking",
    da: 79,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. Social bookmarking with voting.",
    active: true,
  },
  {
    id: "instapaper",
    name: "Instapaper",
    url: "https://www.instapaper.com",
    submitUrl: "https://www.instapaper.com/",
    type: "bookmarking",
    da: 78,
    doFollow: false,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Read-later service owned by Instant Paper.",
    active: true,
  },
  {
    id: "fark",
    name: "Fark",
    url: "https://www.fark.com",
    submitUrl: "https://www.fark.com/submit",
    type: "community",
    da: 75,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. News aggregator and commentary.",
    active: true,
  },
  {
    id: "dzone",
    name: "DZone",
    url: "https://dzone.com",
    submitUrl: "https://dzone.com/links",
    type: "community",
    da: 74,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. Developer-focused content sharing.",
    active: true,
  },
  {
    id: "bizsugar",
    name: "BizSugar",
    url: "https://www.bizsugar.com",
    submitUrl: "https://www.bizsugar.com/submit",
    type: "community",
    da: 70,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. Small business content sharing.",
    active: true,
  },
  {
    id: "growthhackers",
    name: "GrowthHackers",
    url: "https://growthhackers.com",
    submitUrl: "https://growthhackers.com/posts/new",
    type: "community",
    da: 68,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. Growth and marketing community.",
    active: true,
  },
  {
    id: "weheartit",
    name: "We Heart It",
    url: "https://weheartit.com",
    submitUrl: "https://weheartit.com/",
    type: "social",
    da: 67,
    doFollow: false,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Visual bookmarking. Image-focused content.",
    active: true,
  },
  {
    id: "start",
    name: "Start.me",
    url: "https://start.me",
    submitUrl: "https://start.me/",
    type: "bookmarking",
    da: 64,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. Personal start page with bookmarks.",
    active: true,
  },
  {
    id: "raindrop",
    name: "Raindrop.io",
    url: "https://raindrop.io",
    submitUrl: "https://app.raindrop.io/",
    type: "bookmarking",
    da: 62,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. Modern bookmark manager with public collections.",
    active: true,
  },

  // ========== Lower DA but valuable (40-59) ==========
  {
    id: "papaly",
    name: "Papaly",
    url: "https://papaly.com",
    submitUrl: "https://papaly.com/",
    type: "bookmarking",
    da: 55,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. Social bookmarking boards.",
    active: true,
  },
  {
    id: "symbaloo",
    name: "Symbaloo",
    url: "https://www.symbaloo.com",
    submitUrl: "https://www.symbaloo.com/",
    type: "bookmarking",
    da: 54,
    doFollow: true,
    free: true,
    requiresAccount: true,
    method: "form-post",
    notes: "Dofollow. Visual bookmark manager.",
    active: true,
  },
  {
    id: "alltop",
    name: "AllTop",
    url: "https://alltop.com",
    submitUrl: "https://alltop.com/submission",
    type: "bookmarking",
    da: 52,
    doFollow: true,
    free: true,
    requiresAccount: false,
    method: "form-post",
    notes: "Dofollow. Curated topic-based content.",
    active: true,
  },
  {
    id: "trello-public",
    name: "Trello (Public Boards)",
    url: "https://trello.com",
    submitUrl: "https://trello.com/",
    type: "bookmarking",
    da: 92,
    doFollow: false,
    free: true,
    requiresAccount: true,
    method: "manual",
    notes: "Create public boards with bookmarked links.",
    active: true,
  },
  {
    id: "linkatopia",
    name: "Linkatopia",
    url: "https://www.linkatopia.com",
    submitUrl: "https://www.linkatopia.com/submit",
    type: "bookmarking",
    da: 42,
    doFollow: true,
    free: true,
    requiresAccount: false,
    method: "form-post",
    notes: "Dofollow. Simple link bookmarking.",
    active: true,
  },
  {
    id: "bsocial",
    name: "Social Bookmarking Net",
    url: "https://socialbookmarking.net",
    submitUrl: "https://socialbookmarking.net/submit.php",
    type: "bookmarking",
    da: 40,
    doFollow: true,
    free: true,
    requiresAccount: false,
    method: "form-post",
    notes: "Dofollow. Direct form submission.",
    active: true,
  },
  {
    id: "url-submission",
    name: "URL Submission",
    url: "https://www.urlsubmission.net",
    submitUrl: "https://www.urlsubmission.net/submit.php",
    type: "bookmarking",
    da: 38,
    doFollow: true,
    free: true,
    requiresAccount: false,
    method: "form-post",
    notes: "Dofollow. Simple URL submission.",
    active: true,
  },
  {
    id: "addthismark",
    name: "AddThisMark",
    url: "https://www.addthismark.com",
    submitUrl: "https://www.addthismark.com/submit.php",
    type: "bookmarking",
    da: 35,
    doFollow: true,
    free: true,
    requiresAccount: false,
    method: "form-post",
    notes: "Dofollow. Social bookmarking submission.",
    active: true,
  },
  {
    id: "bookmax",
    name: "Bookmax",
    url: "https://www.bookmax.net",
    submitUrl: "https://www.bookmax.net/submit.php",
    type: "bookmarking",
    da: 33,
    doFollow: true,
    free: true,
    requiresAccount: false,
    method: "form-post",
    notes: "Dofollow. Bookmark submission.",
    active: true,
  },
  {
    id: "ezyspot",
    name: "Ezyspot",
    url: "https://www.ezyspot.com",
    submitUrl: "https://www.ezyspot.com/submit.php",
    type: "bookmarking",
    da: 32,
    doFollow: true,
    free: true,
    requiresAccount: false,
    method: "form-post",
    notes: "Dofollow. Quick link submission.",
    active: true,
  },
  {
    id: "blokube",
    name: "Blokube",
    url: "https://www.blokube.com",
    submitUrl: "https://www.blokube.com/submit.php",
    type: "bookmarking",
    da: 30,
    doFollow: true,
    free: true,
    requiresAccount: false,
    method: "form-post",
    notes: "Dofollow. Blogging-focused bookmarks.",
    active: true,
  },
];

export default platforms;
